version: 2.1

jobs:
  Build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm run lint
  Test:
    docker:
      - image: circleci/node:13.8.0.
    steps:
      - checkout
      - run: npm run test
  Analyse:
    docker:
      - image: circleci/node:13.8.0.
    steps:
      - checkout
      - run: npm audit
workflows:
  say-hello-workflow:
    jobs:
      - Build
      - Test:
         requires:
          - Build
      - Analyse:
         requires:
            - Test
